---
galaxy_info:
  author: Saeid Aliei
  description: Install Foreman provisioner
  company: Area Science Park
  role_name: foreman
  namespace: orfeo
  license: GPL-3.0-or-later
  min_ansible_version: "2.1"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - foreman
    - pxeboot
dependencies: []
