---
galaxy_info:
  author: Saeid Aliei
  description: Install a web server, either Nginx or Apache
  company: Area Science Park
  role_name: webserver
  namespace: orfeo
  license: GPL-3.0-or-later
  min_ansible_version: "2.1"
  platforms:
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - webserver
    - pxeboot
dependencies: []
