---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Include orfeo.netboot role
      ansible.builtin.include_role:
        name: orfeo.netboot
